### ISSUE TITLE
We need a wiki

### ISSUE THREAD

**Issue by Sadoon-AlBader** [kth5/archpower#13]
Two important things need to be in the wiki:

1- Install guide, similar to the vanilla Arch install guide, but with added steps for ppc and ppc64le devices, especially with GRUB and such.
2- How to contribute to ArchPOWER: we'll include the two methods we use: your docker method, and my devtools method, so that other people can contribute to the project easily.

**Comment by kth5** [comment]
Enabled Wiki. I won't have time to write too much but I'm welcome to document specific questions.

The contribution to ArchPOWER I'd like to keep as PR only for now an roll with it as they come. Currently there have been only a handful and thus it can easily be hanled that way.

https://github.com/kth5/archpower/wiki
