### ISSUE TITLE
[powerpc32] pgp keys outdated/missing

### ISSUE THREAD

**Issue by crazycusti** [kth5/archpower#28]
hello!

the pgp keys are outdated or missing in the lastest powerpc32 image. my dirty workaround is to set SigLevel = Never in /etc/pacman.conf

greets

**Comment by kth5** [comment]
I updated the `archpower-keyring` package recently (applies to all 3 architectures). But the installer has an issue not executing the pacman-init systemd service unit correctly.

If you run `pacman-key --init` manually it'll work or you can `pacman -S archpower-keyring` on a running system once more while `SigLevel = Never`.

I'm working this out as I go but hints welcome.

**Comment by kth5** [comment]
The problem seems to be a buggy `haveged` systemd.service on `powerpc`.

**Comment by kth5** [comment]
Problem fixed and new ISO on the way.

**Comment by kth5** [comment]
Fixed in new ISOs.

https://archlinuxpower.org/iso/beta/archpower-2022.01.11-powerpc.iso
