### ISSUE TITLE
Xserve G5 - Linux Kernel - Windfarm_rm31 missing

### ISSUE THREAD

**Issue by crazycusti** [kth5/archpower#29]
Hello,

the windfarm_rm31 module is missing in the actual linux-kernel package.

now my xserve g5 is a big jet ;)

on the installation cd i had no problems, the module load exists and load without problem.

**Comment by kth5** [comment]
Fixed in linux-ppc-5.14.16-2. Unfortunately I don't have any G5 hardware let alone an xserve around. So would appreciate feedback. :)

**Comment by crazycusti** [comment]
[   13.505339] windfarm: Initializing for desktop G5 with 1 chips
[   13.687315] windfarm: CPUs control loops started.


my neighbors are relieved.. 💯  thanks!
