### ISSUE TITLE
[ppc32] pacman cannot find mesa package

### ISSUE THREAD

**Issue by crazycusti** [kth5/archpower#32]
hi!

pacman cannot find the mesa package

mesa in package database = 21.2.4-1 
mesa on package repo = 21.2.5-1

ive tried pacman -syyu, to be sure the database is uptodate. it is my fault? or is the database in the repo older than the packages?

greets :)

**Comment by kth5** [comment]
What's your pacman.conf?

**Comment by kth5** [comment]
Latest `pacman-6.0.1-3` fixes the issue but ensure your `pacman.conf` is updated.
