### ISSUE TITLE
PowerBook G4 - Installation works fine, but boots to "Unable to open an initial console" followed by a kernel panic

### ISSUE THREAD

**Issue by DistroHopper39B** [kth5/archpower#34]
The computer I am using is a PowerBook G4 12 inch from 2005. Here are the specs: https://everymac.com/systems/apple/powerbook_g4/specs/powerbook_g4_1.5_12.html

This does not happen off the CD, just the internal HDD. At the same stage on the CD I get a bunch of nouveau messages. What am I doing wrong?

What I've tried:
Installing xf86-video-nouveau drivers (using pacman -S, nothing else)

Image of my issue:
![PXL_20220221_144224000](https://user-images.githubusercontent.com/76637604/154977183-7b4fedac-3618-4203-bdfc-f23f76f3c63c.jpg)

**Comment by kth5** [comment]
I think you may want to install `systemd-sysvcompat` as here it may not be able to start `init` from what it looks like. 

Alternatively you can provide `init=/usr/lib/systemd/systemd` on the kernel cmdline during boot.

**Comment by DistroHopper39B** [comment]
> I think you may want to install `systemd-sysvcompat` as here it may not be able to start `init` from what it looks like.
> 
> Alternatively you can provide `init=/usr/lib/systemd/systemd` on the kernel cmdline during boot.

That package is already installed, and the second command you tried doesn't work.

**Comment by kth5** [comment]
Alternatively, I can see you are using `linux-g4`. Would it be possible to compare to `linux` which isn't optimized for G4 but packaged more recently?

**Comment by DistroHopper39B** [comment]
> Alternatively, I can see you are using `linux-g4`. Would it be possible to compare to `linux` which isn't optimized for G4 but packaged more recently?

Still... doesn't work. I also tried reinstalling systemd with no luck.
![PXL_20220221_152352690](https://user-images.githubusercontent.com/76637604/154984291-45590176-7398-44dd-88cb-c0f6f868ac0b.jpg)

**Comment by kth5** [comment]
That is indeed an odd issue. The install ISO boots and lets you install while you can't boot from the installed system while it already loaded the kernel (Grub installed OK etc).

Things to check:
* arch-chroot from the booted ISO and `mkinitcpio -p linux` does produce errors? I.e. problem in `initramfs`.
* what filesystem do you use that hold `/boot`?

**Comment by DistroHopper39B** [comment]
Here is my /etc/fstab because that might be causing problems:

![PXL_20220221_153644743](https://user-images.githubusercontent.com/76637604/154986776-cc603a1b-e47f-4171-a162-6022324a27a1.jpg)

- returns no errors (besides missing firmware on fallback kernel)
- ext4 (/boot/grub is hfs)

Also, I've had none of these issues on debian powerpc (which has almost no software support) or adelie linux

**Comment by DistroHopper39B** [comment]
> Here is my /etc/fstab because that might be causing problems:
> 
> ![PXL_20220221_153644743](https://user-images.githubusercontent.com/76637604/154986776-cc603a1b-e47f-4171-a162-6022324a27a1.jpg)
> 
> * returns no errors (besides missing firmware on fallback kernel) but those are warnings anyway
> * ext4 (/boot/grub is hfs)
> 
> Also, I've had none of these issues on debian powerpc (which has almost no software support) or adelie linux

I am going to try deleting one of the entries for / in fstab. Maybe that would work?

**Comment by kth5** [comment]
Fix will come with linux `5.16.10.arch1-2` (linux-g4 a little later).

**Comment by kth5** [comment]
Tested on a macmini G4 and two powerbooks. Closing.
