### ISSUE TITLE
Merge RISC-V resources with existing Arch Linux RISC-V effort

### ISSUE THREAD

**Issue by benthetechguy** [kth5/archpower#35]
There is already an effort to port Arch Linux to RISC-V, headed by Felix Yan (felixonmars). The main goal is to make riscv64 an officially supported architecture in Arch Linux, and that's more attainable than with other architectures since we have TUs like felixonmars working on things.
I noticed that this project is also attempting to port Arch to riscv64, so I just wanted to inform you about the existing effort as to not waste resources.
More info is available on the [unofficial website](https://archriscv.felixc.at) and [Matrix room](https://matrix.to/#/#archlinux-riscv:matrix.org).

**Comment by benthetechguy** [comment]
I also noticed the Nezha was the physical device you're using for bootstrapping. I'm actually the person working on getting the above mentioned Arch RISC-V port running on the Nezha, getting pretty close.

**Comment by kth5** [comment]
I primary do not want to get involved in upstream and do things at my own pace. I am not keen on ever becoming an official port for various reasons. Anyone is welcome to use my work here though. :)

I moved away from the Nezha for the lack of documentation and quirks necessary. It works but it's very meh. Moved on to sponsored Starfive Visionfive V1 which is a much more viable platform.

**Comment by benthetechguy** [comment]
Not saying you have to get involved in anything, just that it's kind of a
waste of resources having two separate porting efforts going on.

**Comment by kth5** [comment]
It's not that much effort when you already do 2 platforms and add a third. Semi-automation and patching happens at the same time with the other two.

For me it's a pet project that I use intensively myself first and foremost.

ppc64le for workstation use
ppc for mobile
riscv64 for fun and to be future proof
