### ISSUE TITLE
yaboot iso and install instructions

### ISSUE THREAD

**Issue by benthetechguy** [kth5/archpower#36]
I've found that yaboot is generally more reliable than GRUB on ppc, so I think it's important to give the user a choice between yaboot or GRUB in the installation page for New World machines. I would do this myself, but there's no way to PR a wiki change and this repo doesn't have wiki editing enabled.

**Comment by kth5** [comment]
I have yet to encounter a ppc32 machine that can't PreP or boot with Grub. I'm considering adding _yaboot_ to the repo if someone provides a PR with patches to get it to even just build (it's been unmaintained for years).

**Comment by benthetechguy** [comment]
My iMac G3 gets stuck here booting any GRUB image (tried Gentoo, Debian, and this Arch POWER image):
![IMG_20220317_185707](https://user-images.githubusercontent.com/29379327/158909317-1d145b5a-3304-4599-b4d2-67b755080511.jpg)

If we do manage to package yaboot, it would be helpful to have an iso available that uses yaboot instead of GRUB.

**Comment by kth5** [comment]
This looks more like a problem with RAM limitations and somehow not being able to load the SquashFS properly. How much RAM do you have in this box?

**Comment by kth5** [comment]
Rather than providing just Yaboot, if there is demand a low memory version of the Image could be in order with all but the most essential drivers removed. Like, only provide ext4 and a small list of PATA/SATA controllers.

**Comment by kth5** [comment]
Added a page in the wiki on minimum requirements:
https://github.com/kth5/archpower/wiki/Powerpc-%7C-Minimum-Requirements

**Comment by kth5** [comment]
Ran some tests and the powerpc installer needs at least 180MB RAM to boot but pacstrap will fail without swap.

**Comment by kth5** [comment]
I got yaboot to build and run. I am unable to load any of my systems with it though so I am going to limit myself to Qemu at this stage.

It seems there are many limitations, like not having support for filesystems larger than 8GiB, no btrfs etc etc

**Comment by kth5** [comment]
Latest PowerPC ISO has yaboot aded to the image and you can manually select it to boot with.

ISO: https://archlinuxpower.org/iso/beta/archpower-2022.03.24-powerpc.iso{,sig}

One the how, new wiki section:
https://github.com/kth5/archpower/wiki/Installation-%7C-PowerPC-Common-Problems

**Comment by benthetechguy** [comment]
Thank you so much! I didn't even think about an iso that could use both bootloaders; my brain was stuck in x86 BIOS mode where you could only use one or chainload them.

**Comment by benthetechguy** [comment]
New problems… on the G3, yaboot can't find any valid partitions. I tested in QEMU, and it turns out your image's partition is type `Apple-HFS` while it should be `Apple-Bootstrap`. On top of this, it doesn't solve the G4's issue since GRUB is still the default. Unfortunately, to solve this, a yaboot-specific image would need to be made.

**Comment by kth5** [comment]
Hmm, this can be done on the same image tho. Need to find out how.

**Comment by benthetechguy** [comment]
Good and bad news. My G4's motherboard has died, so I no longer have a need for yaboot. I'm purchasing a memory upgrade for my G3 that should bring it up to 1 GB and hopefully get arch running. Thanks for all your help with this, and sorry for the massive inconvenience!
After some investigation on the debian-powerpc mailing list, I believe the culprit of the GRUB failures may have been some sort of bizarre memory issue, since the system's RAM was mixed and matched, and a few others have reported similar problems. The idea is that the memory is messed up in a very minor way so that normal usage is not affected and most bootloaders can get by, but GRUB touches so much more memory that it's more likely to run into problems.
Thanks again for all your help dealing with this issue.
