### ISSUE TITLE
32bit PowerPC support

### ISSUE THREAD

**Issue by kth5** [kth5/archpower#5]
Shouldn't be too hard to rebuild packages to support his. Work on the installer is needed though to ensure archlive can generate a working one.

Think about how to automate builds when updating ppc64le.

**Comment by crazycusti** [comment]
hey!

i would like to help for powerpc32, powerpc64 (BE) but my programming/porting skills is not so good. The last years i tried many ArchPPC builds, but with no success.

-> https://github.com/crazycusti/Arch-Linux-PPC

i had many PowerPC-devices.. G3, G4, G4 MDD, G5, PowerBooks, iBooks.. of course an xserve g5 too! So automated builds-devices or test-devices are available. 

i never really work with docker, so i had no idea where start from. blind crosscompile would be a totally chaos, i tried so often.

**Comment by kth5** [comment]
That's cool news someone has interest still!

I'd personally refuse to actually build on those old-skool Apple computers. Firstly, they are wholly inefficient power consumption wise and secondly most of the time are actually unable to build certain packages with LTO enabled. Chrome, Python (3.x) etc come to mind where the maxed out RAM in a G4 based machine will not accommodate or the 32bit address space prohibit it from allocating enough on a G5. I'm reluctant to also provide ppc64 BE builds all things considered, at least not without full automation which I haven't had time for so far.

What would be cool though is regular testing on these. I only have a MacMini G4 1.25GHz with maxed out RAM at 1GiB here for instance.

What I've already got is available here:
```
[base32]
Server = https://archlinuxpower.org/base-ppc32/
```
DM me at alex.bldck@gmail.com if you have any ideas on how to contribute already and have any insight on how you imagine your collaboration.

**Comment by kth5** [comment]
First powerpc ISO:
https://archlinuxpower.org/iso/alpha/archpower-2020.10.04-powerpc.iso

* no ppc64 kernel so can only boot on 603 up to 74xx.

**Comment by kth5** [comment]
New ISO out with above pacman.conf issue fixed:
https://archlinuxpower.org/iso/alpha/archpower-2020.10.06-powerpc.iso

**Comment by crazycusti** [comment]
i will tried the images on friday.. 

yesterday, i boot up successful the 10.04 iso on qemu!

**Comment by kth5** [comment]
Boots fine on Qemu but still not on my Mac Mini G4 where it halts with an illegal memory access and drops back to OF.

**Comment by crazycusti** [comment]
yes, same on powerbook g4

https://dump.chrisnew.de/upload/data/public/IMG_20201008_184005.jpg

**Comment by kth5** [comment]
New ISO available:
https://archlinuxpower.org/iso/archpower-current-powerpc.iso

Fixes:
* boots on PowerBook G4 Aluminium

Problems:
* when booting from CD, most of the time the volume label isn't picked up so has to manually be mounted and shell exited twice via CTRL+D
```
mount /dev/sr0 /run/archiso/bootmnt
^D
^D
```

**Comment by kth5** [comment]
Last night got accellerated X.org working on PowerBook G4 Aluminium:
```
pacman -Sy linux # reinstall/update to 5.9.0-1 from mirror
pacman -S xf86-video-ati linux
cmdline: video=offb video=radeonfb:off radeon.agpmode=-1 radeon.modeset=1
```

**Comment by kth5** [comment]
How to use Grub for booting:

* create a bootstrap partition with at least 4MiB size (default 800KiB is too small)
![image](https://user-images.githubusercontent.com/1784992/96678365-d7577f80-1371-11eb-8e5f-39cc03722fce.png)

* install as normal (assumed to /mnt)
```
pacstrap /mnt/ base linux grub hfsutils
```

* format bootstrap partition (/dev/sda2) from target (no hfsutils on iso yet)
```
hformat /dev/sda2
```

* mount bootstrap partition (assumed /dev/sda2) to /boot/grub on the target rootfs
```
mkdir /mnt/boot/grub
mount /dev/sda2 /mnt/boot/grub
arch-chroot /mnt
> grub-mkconfig -o /boot/grub/grub.cfg
> grub-install
```
> mount /de

**Comment by kth5** [comment]
@crazycusti Das macht es fuer Dich einfacher, nur leider nicht fuer den Rest der Welt. ;)

**Comment by kth5** [comment]
X stable as can be with somewhat accelerated state:

![image](https://user-images.githubusercontent.com/1784992/96884754-268cd580-1482-11eb-9f90-2b3af5e42fd7.png)

Using Midori as a browser here (webkit2gtk based). It's slow, not very feature rich but does the trick for looking things up.

Have a Firefox 82.0 build ready for ppc but it segfaults. Debugging required and I seriously do not want to go the ArcticFox route.

**Comment by kth5** [comment]
New ISO out for ppc/ppc64:

https://archlinuxpower.org/iso/alpha/archpower-2021.01.20.1-powerpc.iso

**Comment by kth5** [comment]
Since ISO is out and we've had successful installs on G5 and G4 hardware, I consider this done for the moment.
