### ISSUE TITLE
Electron Not Available - Unable to Install Discord via AUR

### ISSUE THREAD

**Issue by iamhumanipromise** [kth5/archpower#56]
It seems like AUR solutions require Electron 22-24 or XDG which fail to build. 

Anyone have any luck with compiling those? ASAR then needs to build and BLAM discord.

**Comment by kth5** [comment]
That depends on the architecture you are using. Potentially you could patch together Electron (much line in termas of Chromium) which is a ton of work but doable. But that only really on `powerpc64le`. Chromium/V8 is not support on any other powerpc* for instance.
