### ISSUE TITLE
password installer-iso?

### ISSUE THREAD

**Issue by crazycusti** [kth5/archpower#6]
I booted up the latest installer iso but i needed a root password? i try many variations..

**Comment by kth5** [comment]
VGA console does auto login:
![image](https://user-images.githubusercontent.com/1784992/93670657-4f920300-fa9d-11ea-90d8-ffd9dda1b432.png)

While serial seems to that have that issue. Am looking into it as I write this.

**Comment by kth5** [comment]
New ISO up with root password for serial set to "arch".

https://archlinuxpower.org/iso/alpha/archpower-2020.09.19-powerpc64le.iso

More permanent solution coming up.

**Comment by crazycusti** [comment]
ok thanks!

the win64-qemu build crash with vga console. so i must use serial :(
