### ISSUE TITLE
systemd built against the wrong version of glibc

### ISSUE THREAD

**Issue by DistroHopper39B** [kth5/archpower#61]
Since the last ISO release, systemd has been updated in your repositories to require glibc 2.38 (see attached) but glibc hasn't been updated to support this version of systemd. This results in an unbootable system.

Edit: It's worth noting that the correct glibc version is in the `testing` repository. Enabling that repository and installing ArchPOWER works fine. Was the systemd version accidentally pushed to `main` instead of `testing`?

![IMG_0705](https://github.com/kth5/archpower/assets/76637604/e68fe7d0-4f3a-42bf-9c51-bb3ff6a1da5e)

**Comment by kth5** [comment]
A new release is imminent and there are a few showstoppers actually regarding `systemd-udevd` segfaulting on `powerpc` with kenerls newer than `lts` which currently hangs at `6.1.x`. 

At the moment, using the previous installer ISO should alleviate the above problem:
https://archlinuxpower.org/iso/stable/archpower-2022.12.10-powerpc.iso

**Comment by kth5** [comment]
Fixed in latest release ISO:
https://archlinuxpower.org/iso/stable/archpower-2023.08.19-powerpc.iso

**Comment by kth5** [comment]
Fixed in latest release ISO:
https://archlinuxpower.org/iso/stable/archpower-2023.08.19-powerpc.iso
