### ISSUE TITLE
Repo SSL Invalid

### ISSUE THREAD

**Issue by KaoGomi** [kth5/archpower#63]
Not sure if that is a proper descriptor, but when I try to install ArchPOWER I am met with this error...
```shell
error: failed retrieving file 'base-any.db' from repo.archlinuxpower.org : SSL certificate problem: certificate is not yet valid
error: failed to synchronize all databases (download library error)
==> ERROR: Failed to install packages to new root
``` 
... and it prohibits me to progress further in the install process. 

I've tried repopulating the keyring as well, but this didn't work.

**Comment by kth5** [comment]
This sounds like your local clock isn't set correctly and is running well in the past. Please set it to a correct date and try again.

**Comment by KaoGomi** [comment]
That was the issue. Seems like drinking and installing Linux didn't mix for me. Totally user error.

**Comment by kth5** [comment]
Happens to the best of us! :1st_place_medal:
