### ISSUE TITLE
Repo doesn't have ppc64 big endian kernel

### ISSUE THREAD

**Issue by ostrich** [kth5/archpower#64]
At least as far as I can tell. It also isn't in https://repo.archlinuxpower.org/base/powerpc64/

```
root@archiso ~ # pacstrap -K /mnt base linux linux-firmware base-devel neovim
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
 base-any is up to date
 base is up to date
error: target not found: linux
error: target not found: neovim
==> ERROR: Failed to install packages to new root
```

**Comment by kth5** [comment]
There is one in any that is being shared with the powerpc port to enable 64bit systems with 32bit userland.

This package is linux-ppc64. I will add an item to the docs about this.

**Comment by kth5** [comment]
Note added in the NewWorld installation guide.

**Comment by kth5** [comment]
Table on which kernels are currently available:
https://github.com/kth5/archpower/wiki/Available-kernels
