### ISSUE TITLE
Access To Remote PowerPC

### ISSUE THREAD

**Issue by mrbubzie93** [kth5/archpower#70]
Hey had no way to contact you so I apologize in advance for posting this as an issue when it’s not, but I wanted to offer my Powermac G5, iMac G5 iSight and PowerBook G4 if you need systems to remote into for development/compiling purposes. Just let me know if you need anything! I don’t know programming but I’d like contribute in some way if you need.

**Comment by mrbubzie93** [comment]
Was the konsole fit yet for kde?

**Comment by kth5** [comment]
I have 96 threads of OpenPOWER under my desk so just build power isn't really needed. More hands would be something.

`konsole` has been "fixed" by altering defaults on `powerpc`.
