### ISSUE TITLE
Broken KDE-Networking KDE-Applications 

### ISSUE THREAD

**Issue by bradylegend32** [kth5/archpower#72]
It appears that the Plasma Meta set installs correctly, but there seems to be an issue with the KDE-networking and KDE-applications dependencies. They appear to be either broken or conflicting with each other, preventing both installations with and without testing enabled. Additionally, User-Manager is also broken.

**Comment by kth5** [comment]
`[testing]` has Plasma 6 RC2 now in preparations for the full release. The meta packages have been fixed up there an install on all supported architectures.

Further announcements will follow tomorrow.
