### ISSUE TITLE
KDE Alternative And Email

### ISSUE THREAD

**Issue by mrbubzie93** [kth5/archpower#76]
Hey, thanks for the continued work. It might be worth just dropping KDE Plasma and instead building the Trinity Desktop located [here](https://www.trinitydesktop.org/). I have it compiled, and because it's based on KDE 3.5, it's so much lighter and makes way more sense than supporting KDE Plasma... that's so much work for you. The desktop is actively maintained and so far has been as simple as compiling for me, no issues at all. The other thing was email and browsing. I noticed there are not a lot of email clients. A lightweight email client I found was Claws Mail located [here](https://www.claws-mail.org/git.php), easy to build and extremely lightweight for older hardware. And last but not least is Wicknix maintained SeaLion Web browser. This has the same base as ArcticFox but built off a new backend called XUL which is derived from palemoon, which includes more modern APIs than ArcticFox and is even lighter in my testing and capable of far for compatability modern sites. Wicknix has been developing PowerPC software alongside Cameron, who up until recently was maintaining TenFourFox for PPC. Same build requirements as ArcticFox. I have it compiling, and I've actually changed over to it because ArcticFox is aging and it is located [here](https://github.com/wicknix/SeaLion). Hope this doesnt come off as making or requesting you do more work…primarily submitting this because I know the pains of compiling and maintaining…I was just trying to find solutions that will make it easier and more efficient to maintain. Anyways like I said you should look into trinity instead of building kde 6…its the best solution for a kde person wanting to use it on older hardware and its got the  caveat of being built on a mature kde 3.5 backend which means lean and mean and not having to deal with weekly releases of kde 6 causing you having to worry about compatibility as new versions are released of kde 6… and the beautiful thing is everything is in the AUR….cheers!!!

**Comment by kth5** [comment]
I appreciate and exhaustive expression of interest but please file bug reports and feature requests here that can be acted on. As short as can be and as long as need be please.

SeaLion is broken. There is no documentation, the girhub repo has broken submodules to non-existant repositories and so forth. There is no AUR entry I could find neither to take a reference. I am content using NetSurf, Midori/Epiphany or Articfox when I am at my `powerpc` box. I personally would not want to spend any further time on this one browser, when options are plenty and hundreds of other packages need to be kept updated. Sorry.

Claws and the like I personally do not use. Another DE is a heck lot of work. PRs welcome but no guarantees it will be kept up to date by anyone else but you. ;)


For reference, the work required to keep the current wet of packages updated does not currently first into a work month when accounting for manual labour as well as CPU time.

**Comment by mrbubzie93** [comment]
huh sealion builds fine for me and I also have palemoon working along with tribity desktop. Alright thank you!
Sent from my iPhone

On Apr 20, 2024, at 6:11 AM, Alexander Baldeck ***@***.***> wrote:

﻿

I appreciate and exhaustive expression of interest but please file bug reports and feature requests here that can be acted on. As short as can be and as long as need be please.

SeaLion is broken. There is no documentation, the girhub repo has broken submodules to non-existant repositories and so forth. There is no AUR entry I could find neither to take a reference. I am content using NetSurf, Midori/Epiphany or Articfox when I am at my powerpc box. I personally would not want to spend any further time on this one browser, when options are plenty and hundreds of other packages need to be kept updated. Sorry.

Claws and the like I personally do not use. Another DE is a heck lot of work. PRs welcome but no guarantees it will be kept up to date by anyone else but you. ;)

For reference, the work required to keep the current wet of packages updated does not currently first into a work month when accounting for manual labour as well as CPU time.
