### ISSUE TITLE
patch for none working kde6 acceleration.

### ISSUE THREAD

**Issue by mrbubzie** [kth5/archpower#80]
Hey just wanted to give you a heads up on something that was shared to me by the folks over at Adeline’s project as they have full acceleration without the need for software rendering…. https://cgit.adelielinux.org/packages/tree/user/qt5-qtdeclarative/endian.patch

attached are the lines they patched to render kde differently then normal.

**Comment by mrbubzie** [comment]
![IMG_4126](https://github.com/kth5/archpower/assets/146482519/ceb13023-11d1-4fe2-87c9-216644623a3e)

**Comment by kth5** [comment]
The patch is is already with `qt5-declarative` in Arch POWER. And it indeed does disable QtQuick acceleration. For Qt6 a similar patch also needed adding and has been already.

Hardware acceleration in QtQuick has been broken on big endian for a very long time (starting with 5.x I believe). The mentioned patch as well as the ones included in Arch POWER, set rendering to software only on big median.
