### ISSUE TITLE
Installation in qemu hangs in grub-mkconfig

### ISSUE THREAD

**Issue by vasi** [kth5/archpower#88]
I'm testing in qemu before trying a real installation on my iBook G3. 

Following [this guide](https://github.com/kth5/archpower/wiki/Installation-%7C--NewWorld-PowerMac-with-Grub), when I run `grub-mkconfig -o /boot/grub/grub.cfg` inside the chroot, the process just hangs.

My rudimentary attempts to investigate:
* `pstree` shows this is happening within the `00_header` script, as it calls `grub-probe -t fs /usr/share/grub/unicode.pf2`
* Attempting to kill grub-probe doesn't work, even with `kill -9`!
* If I run `grub-probe` again myself with the `-v` flag, the last line I see printed is `Scanning for mdraid1x devices on disk`
* Attempting to strace, the last thing I see is a BSKFLSBUF ioctl on /dev/sda3. But that line was cut off in the middle, so it's possible there's other stuff going on that just got stuck in the buffer.
* If I reboot, and run `grub-probe` _before_ trying to `grub-mkconfig`, the grub-probe works fine!? Super confusing! But `grub-mkconfig` after that still hangs.
* I tried skipping grub-mkconfig and just doing grub-install, I again get a hang. But it looks like a totally random place, when it's copying a `.mo` file to the bootstrap partition.

I've been testing with qemu 6.2.0, and with the archpower-current-powerpc.iso from 2024-05-05. I'm starting the emulator with:

```
qemu-system-ppc -L pc-bios -M mac99,via=pmu -m 640m -net nic -net user,hostfwd=tcp::2222-:22 -drive format=qcow2,discard=unmap,file=archpower.qcow2 -drive media=cdrom,file=archpower-current-powerpc.iso -prom-env 'boot-device=cd:,\\:tbxi'
```

**Comment by vasi** [comment]
Also happy to do any experiments that will help you repro, or investigate further with some guidance.

**Comment by vasi** [comment]
While I'm here, some small notes about the installation instructions:

1. There's a type in the line about genfstab, it's missing the `>` character to redirect the output.
1. You may want to recommend the `--no-nvram` argument to grub-install, since I've never seen setting the setting of boot-device succeed.

**Comment by vasi** [comment]
Hmm, it looks like switching from 640 MB to 2 GB of RAM is enough to get grub-mkconfig and grub-install to work! This is super weird, because it looks like I have lots of RAM available even with just 640 MB during grub-mkconfig. `top` shows:

* ~90 MB free
* 460 MB of cache
* 2 GB of unused swap

**Comment by vasi** [comment]
Hm, I was not able to repeat this working, even with 2 GB of RAM. Perhaps disregard that previous comment, unless I can repro.

**Comment by vasi** [comment]
Ah, I've found it. The problem seems to be with a (non-plus) HFS boot dir. If I install hfsprogs, and make it HFS+ instead, everything goes smoothly.

I'm not sure what specifically about HFS was making things break, but I now have a working (virtual) system.

Maybe we could add a note to the install page to use HFS+ instead of HFS? I don't think there's any advantage to HFS, any New World Mac will support HFS+ in ROM.

**Comment by kth5** [comment]
Just got back from an extended vacation over the summer almost gully afk, thus the late jump on this.

Real hardware testing is what I do mostly on G4 based systems and lately started to experiment on DingusPPC. Tbh though I have not had much luck with Grub on ppc32, yaboot may work better which is available for powerpc and powerpc64.

I will run more tests soon, at this time the ISO with Grub boots on ppc32.

When I do VMs I usually prefer running powerpc64 and a 32bit user-land. Gives you SMP support and KVM on supported platforms.

**Comment by vasi** [comment]
Hope you enjoyed your vacation!

I've had a lot of luck with grub on ppc32 so far, at least on my iBook G3. It's definitely a lot more useful in recovery situations, since editing boot arguments is way easier than yaboot.

Interesting idea for testing in qemu, thanks! I didn't realize ppc64 would allow SMP.

**Comment by kth5** [comment]
I wasn't able to reproduce this in Qemu 9.1.0 with your cmdline posted above.

However, I wasn't able to get the VM to boot from `hd:` no matter what I did which is curious. I tried both `grub` and `yaboot`. :-/

**Comment by vasi** [comment]
Hmm let me try:

1. I'm running Ubuntu 24.04.1 amd64, and performing this on 2024-09-21
1. Build qemu 9.1.0 from source. Get build-dependencies by looking at results of `apt --simulate build-dep qemu`, and installing all except libjack* (which conflicts with other packages I need) .
1. Create a 40g qcow2 disk image with qemu-img.
1. Boot the 2024-05-05 powerpc (32-bit) ISO: `./qemu-system-ppc -L pc-bios -M mac99,via=pmu -m 640m -net nic -net user,hostfwd=tcp::2222-:22 -drive format=qcow2,discard=unmap,file=archpower.qcow2 -drive media=cdrom,file=archpower-current-powerpc.iso -prom-env 'boot-device=cd:,\\:tbxi'`
1. Setup network: `dhclient enp0s15`
1. Follow the [installation instructions](https://github.com/kth5/archpower/wiki/Installation-%7C--NewWorld-PowerMac-with-Grub):
    1. Partition with mac-fdisk: 32 MB /dev/sda2 HFS bootstrap (with hformat), rest as /dev/sda3 ext4 root (with mkfs.ext4)
    1. pacstrap: base linux grub hfsutils
    1. Mount bootstrap partition to /mnt/boot/grub
    1. Generate an fstab with genfstab
    1. arch-chroot into /mnt
        1. Create a grub.cfg with grub-mkconfig
        1. `grub-install ---no-nvram`. **It succeeds now, so maybe this bug was just in my earlier version of qemu?**
1. In the chroot, do remaining [Arch install steps](https://wiki.archlinux.org/title/Installation_guide#Time): Timezone, locales, networking ([DHCP](https://wiki.archlinux.org/title/Systemd-networkd#Wired_adapter_using_DHCP) with networkd/resolved), root password 
1. Exit the chroot, unmount filesystems, and shutdown
1. Reboot from the HD: `./qemu-system-ppc -L pc-bios -M mac99,via=pmu -m 640m -net nic -net user,hostfwd=tcp::2222-:22 -drive format=qcow2,discard=unmap,file=archpower.qcow2 -prom-env 'boot-device=hd:,\grub'`. **It boots successfully**
   1. Just in case it's dependent on some installed BIOS files or anything, remove any qemu-related apt packages. Still boots fine.

So, not sure what's going on! I guess we can close this issue if it's only a problem on one specific version of qemu.
