### ISSUE TITLE
libvirt does not build (6.5.0-3)

### ISSUE THREAD

**Issue by Sadoon-AlBader** [kth5/archpower#9]
After building in a clean chroot, libvirt fails in the package phase

make[1]: Leaving directory '/build/libvirt/src/build'
mv: cannot stat '/build/libvirt/pkg/libvirt/usr/lib/libvirt/storage-backend/libvirt_storage_backend_rbd.so': No such file or directory
==> ERROR: A failure occurred in package_libvirt().
    Aborting...

**Comment by kth5** [comment]
ceph 15.2.7 is on the way which should fix this.

**Comment by kth5** [comment]
ceph 15.2.7 is up and rebuilt libvirt as well.
