### ISSUE TITLE
Please, don't upgrade mesa to 24.2.x yet, there's a regression

### ISSUE THREAD

**Issue by Link4Electronics** [kth5/archpower#92]
So, there's a regression on mesa 24.2.x for big endian devices, last working is 24.1.x

More info: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11933
https://gitlab.freedesktop.org/mesa/mesa/-/issues/12048

**Comment by kth5** [comment]
I found issues with anything > 24.1 as well and didn't even get as far as to test run it. Considering there are many other tasks currently underway such as a major rebuild for `powerpc64le` this isn't even on the radar yet. ;)
