### ISSUE TITLE
Remove ppc64abi32 from binfmt-qemu-all-arch

### ISSUE THREAD

**Issue by bobpaul** [kth5/archpower#94]
ppc64abi32 was [removed by Qemu v7](https://www.qemu.org/docs/master/about/removed-features.html#ppc64abi32-cpus-removed-in-7-0) and the current `binfmt-qemu-all-arch` package is causing problems with `systemd-binfmt`.

```
Nov 30 00:50:03 syndicate systemd[1]: Starting Set Up Additional Binary Formats...
Nov 30 00:50:03 syndicate systemd-binfmt[1045]: /usr/lib/binfmt.d/qemu.conf:12: Failed to add binary format 'qemu-ppc64abi32': No such file or directory
Nov 30 00:50:04 syndicate systemd[1]: systemd-binfmt.service: Main process exited, code=exited, status=1/FAILURE
```

It's a straight forward patch, just `sed -i '/qemu-ppc64abi32/d' qemu.conf`. Github wouldn't let me upload it because of the binary characters in the file.

**Comment by kth5** [comment]
`binfmt-qemu-all-arch` has been deprecated in favour of `qemu-user-{,static-}binfmt`. I have removed the former from the repos.
